drop table if exists momo_participant CASCADE;
drop table if exists momo_group CASCADE;
drop table if exists momo_member CASCADE;
drop table if exists momo_schedule CASCADE;
drop table if exists momo_token CASCADE;
drop table if exists momo_favorite CASCADE;
drop table if exists momo_groupimage CASCADE;

create table momo_group
(
    id                   bigint generated by default as identity,
    capacity             integer      not null,
    category             varchar(255) not null,
    deadline             timestamp    not null,
    description          clob         not null,
    endDate              date         not null,
    startDate            date         not null,
    closedEarly          boolean      not null,
    locationAddress      varchar(255) not null,
    locationBuildingName varchar(255) not null,
    locationDetail       varchar(255) not null,
    name                 varchar(50) not null,
    host_id              bigint,
    primary key (id)
);

create table momo_member
(
    id       bigint generated by default as identity,
    deleted  integer      not null default 0,
    user_id  varchar(50) null,
    name     varchar(20)  null,
    password varchar(255) null,
    primary key (id)
);

create table momo_schedule
(
    id        bigint generated by default as identity,
    date      date not null,
    endTime   time not null,
    startTime time not null,
    group_id  bigint,
    primary key (id)
);

create table momo_participant
(
    id        bigint generated by default as identity,
    group_id  bigint,
    member_id bigint,
    primary key (id)
);

create table momo_favorite
(
    id        bigint generated by default as identity,
    group_id  bigint,
    member_id bigint,
    primary key (id)
);

create table momo_token
(
    id           bigint generated by default as identity,
    refreshToken varchar(255) not null,
    member_id    bigint,
    primary key (id)
);

create table momo_groupimage (
     id          bigint generated by default as identity,
     group_id    bigint not null,
     image_name   varchar(255),
     primary key (id)
);
