spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming.physical-strategy: com.woowacourse.momo.config.CustomNamingStrategy
