spring:
  sql.init.mode: always
  datasource:
    username: sa
    url: jdbc:h2:~/momo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true