spring:
  config:
    activate:
      on-profile: local
    import:
      - security/application.yml
      - security/application-local-datasource.yml
      - application-datasource.yml
      - application-logging.yml

  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

momo-log:
  slack: false
  file: false
