spring:
  jpa:
    hibernate:
      naming.physical-strategy: com.woowacourse.momo.global.config.CustomNamingStrategy
  datasource:
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE:10}
#      idleTimeout: 10000
#      connection-timeout: 10000
#      validation-timeout: 10000
#      maxLifetime: 580000
