spring:
  config:
    activate:
      on-profile: prod
    import:
      - security/application.yml
      - security/application-prod-datasource.yml
      - application-datasource.yml
      - application-logging.yml

  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

momo-log:
  slack: true
  file: true
