#spring:
#  jpa:
#    properties:
#      hibernate:
#        format_sql: 'true'
#    show-sql: 'true'
#
#logging:
#  level:
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

momo-logging:
  show: 'true'
  file-path: './momolog/'
